---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# dataclock

<!-- badges: start -->
<!-- badges: end -->

The goal of dataclock is to plot event time on a clock chart. Additionally it 
help you make a day chart, week chart, or month chart, or plan events in 
those periods.

## Installation

You can install the development version of dataclock from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("mahmudstat/dataclock")
```

## Usage

```{r example}
#| fig.alt = "Clock chart of random event times based on a random sample."
library(dataclock)

set.seed(10)
df <- tibble::tibble(hr = sample(0:23, 50, replace = TRUE),
                  mnt = sample(0:59, 50, replace = TRUE),
                  sec = sample(0:59, 50, replace = TRUE),
                  time = paste(hr, mnt, sec, sep = ":"),
                  value = sample(60,50))
p1 <- clock_chart_qnt(df, time, crit = value)
p1 + ggplot2::theme(legend.position = "right")+
ggplot2::labs(title = "Clock chart of random values")
```
